//------------------------------------------------------------------------
// TakeMeIn 16-Band Parametric Equalizer - VST3 Plugin
// Copyright(c) 2024 TakeMeIn
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "TakeMeInEQ.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "TakeMeIn 16-Band Parametric EQ VST3 (64Bit)"
#else
#define stringFileDescription "TakeMeIn 16-Band Parametric EQ VST3"
#endif
#define stringCompanyName "TakeMeIn\0"
#define stringLegalCopyright "Copyright(c) 2024 TakeMeIn."
#define stringLegalTrademarks                                                  \
  "VST is a trademark of Steinberg Media Technologies GmbH"
